Header header
uint64 count
string name
uint32 number

geometry_msgs/Quaternion orientation 
float64[9] orientation_covariance
geometry_msgs/Vector3 linear_acceleration
float64[9] linear_acceleration_covariance 
geometry_msgs/Vector3 angular_velocity
float64[9] angular_velocity_covariance

float64 sample_time

float64 accel_mcu_time
float64 gyro_mcu_time
float64 accel_gps_time
float64 gyro_gps_time
